[project]
name = "verto"
authors = [
    { name = "Webwire", email = "support@webwire.com.au"}
]
description = "Verto operations, safety, planning and mobile workflows for ERPNext Version 16"
requires-python = ">=3.14,<3.15"
readme = "README.md"
dynamic = ["version"]
dependencies = [
    "python-docx>=1.1.0",
    "pywebpush>=2.3,<3",
]

[tool.bench.frappe-dependencies]
frappe = ">=16.0.0,<17.0.0"
erpnext = ">=16.0.0,<17.0.0"
hrms = ">=16.0.0,<17.0.0"
gameplan = ">=0.0.1"
raven = ">=2.0.0,<5.0.0"

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.bench.dev-dependencies]
# package_name = "~=1.1.0"
